# Variables
@baseurl = http://localhost:3333

# Health check
# @name healthCheck
GET {{baseurl}}/health

###

# Get rooms
# @name getRooms
GET {{baseurl}}/rooms

###

# Create room
# @name createRoom
POST {{baseurl}}/rooms
Content-Type: application/json

{
    "name": "Sala de teste #02",
    "description": "Essa é uma sala de teste #02"
}

###

@roomId = {{createRoom.response.body.$.roomId}}


###

# Get room questions
# @name getRoomQuestions
GET {{baseurl}}/rooms/{{roomId}}/questions

###

# Create question
# @name createQuestion
POST {{baseurl}}/rooms/111179ed-6778-47da-3cb9-f8813aabe33b/questions
Content-Type: application/json

{
    "question": "O que é JavaScript?"
}